# Generated by OrchestKit Claude Plugin
# Created: 2026-08-29

"""Rewrite the kit version everywhere it lives. Called by scripts/bump-version.sh.

Sites: .claude-plugin/plugin.json, .claude-plugin/marketplace.json, and per skill
SKILL.md (version:), SKILL_HE.md (version: + the mirrors stamp), metadata.json.
"""

import json
import pathlib
import re
import sys


def main(root: pathlib.Path, new: str) -> int:
    n = 0
    for rel in (".claude-plugin/plugin.json", ".claude-plugin/marketplace.json"):
        p = root / rel
        d = json.loads(p.read_text(encoding="utf-8"))
        if "plugins" in d:
            d["plugins"][0]["version"] = new
        else:
            d["version"] = new
        p.write_text(
            json.dumps(d, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        n += 1
    for skill in sorted((root / "skills").iterdir()):
        if not (skill / "SKILL.md").exists():
            continue
        for name in ("SKILL.md", "SKILL_HE.md"):
            p = skill / name
            if not p.exists():
                continue
            t = p.read_text(encoding="utf-8")
            t = re.sub(r"^version:\s*.*$", f"version: {new}", t, count=1, flags=re.M)
            t = re.sub(
                r"<!-- mirrors SKILL\.md v[0-9.]+ -->",
                f"<!-- mirrors SKILL.md v{new} -->",
                t,
            )
            p.write_text(t, encoding="utf-8")
            n += 1
        m = skill / "metadata.json"
        d = json.loads(m.read_text(encoding="utf-8"))
        d["version"] = new
        m.write_text(
            json.dumps(d, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        n += 1
    print(f"bumped {n} files to {new}")
    return 0


if __name__ == "__main__":
    sys.exit(main(pathlib.Path(sys.argv[1]), sys.argv[2]))
